export {default as Home} from './Home'
export {default as Games} from './games'
export {default as Search} from './search'
export {default as Login} from './login'
export {default as Subscribe} from './subscribe'
export {default as Welcome} from './welcome'
export {default as Contact} from './contact'